# Site settings
title: "Abhijeet Marikal Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Abhijeet Marikal"
resume_title:                   "Cybersecurity Professional"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "marikalabhijeet@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "980-253-5152"
resume_contact_address:         "College Park, Maryland"

resume_header_contact_info:     "College Park, Maryland • 980-253-5152 • marikalabhijeet@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>A dedicated cybersecurity professional with an educational foundation from esteemed institutions such as the University of Maryland and New York University. Armed with hands-on experience ranging from digital forensics at Central Forensic Science Laboratory to cloud security transformations using AWS. Proven expertise in identifying vulnerabilities, Incident Response, implementing robust security measures and Digital Forensics. Seeking opportunities to leverage my technical proficiency and leadership skills in forward-thinking cybersecurity roles.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MarikalAbhijeet"
  resume_twitter_url:           "https://twitter.com/MarikalAbhijeet"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/abhijeetm9/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
